import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#cecfef",
        "on-error": "#fff7f6",
        "outline-variant": "#b2b1b4",
        outline: "#7b7a7d",
        secondary: "#5d5f64",
        background: "#fcf8f9",
        "secondary-dim": "#515358",
        "surface-container-low": "#f6f3f4",
        tertiary: "#5b5d78",
        "on-tertiary-container": "#4c4e69",
        "tertiary-container": "#dcddfe",
        "inverse-primary": "#e4ebfa",
        "primary-dim": "#4c535f",
        "tertiary-dim": "#4f516c",
        "secondary-fixed": "#e1e2e9",
        "on-tertiary-fixed": "#393c55",
        "on-background": "#323235",
        "primary-container": "#dce3f2",
        "on-secondary-container": "#4f5257",
        "secondary-container": "#e1e2e9",
        "surface-bright": "#fcf8f9",
        "on-tertiary-fixed-variant": "#565873",
        "inverse-surface": "#0e0e0f",
        "on-error-container": "#752121",
        "on-surface": "#323235",
        "primary-fixed-dim": "#ced5e3",
        "on-tertiary": "#fbf8ff",
        "inverse-on-surface": "#9e9c9d",
        "surface-container": "#f0edef",
        "on-secondary": "#f8f8ff",
        primary: "#575f6b",
        "surface-variant": "#e3e2e4",
        "surface-tint": "#575f6b",
        "secondary-fixed-dim": "#d3d4da",
        "surface-container-lowest": "#ffffff",
        surface: "#fcf8f9",
        "on-secondary-fixed": "#3d3f44",
        "tertiary-fixed": "#dcddfe",
        "primary-fixed": "#dce3f2",
        "on-primary-fixed-variant": "#555c68",
        "on-secondary-fixed-variant": "#595b61",
        "on-primary-container": "#4b525e",
        "error-container": "#fe8983",
        "surface-container-highest": "#e3e2e4",
        "on-primary": "#f6f7ff",
        "surface-dim": "#dbd9dd",
        "on-surface-variant": "#5f5f61",
        "error-dim": "#4e0309",
        "surface-container-high": "#e9e7ea",
        "on-primary-fixed": "#38404b",
        error: "#9f403d",
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      // Do NOT override borderRadius — use Tailwind defaults
    },
  },
  plugins: [forms],
};

export default config;
