"""Export insight card tables as SQL INSERT statements.

Produces a .sql file that can be loaded on any Postgres instance with
the same schema. Uses ON CONFLICT DO UPDATE so it's safe to re-run.

Usage::

    cd backend
    python -m etl.dump_insight_cards              # writes insight_cards_data.sql
    python -m etl.dump_insight_cards output.sql    # custom filename
"""

from __future__ import annotations

import sys

from app.database import SessionLocal
from app.models import CountyInsightCard, StatewideInsight


def _escape(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''").replace("\n", "\\n") + "'"


def run(output_path: str = "insight_cards_data.sql") -> None:
    db = SessionLocal()
    lines: list[str] = []

    lines.append("-- Insight card data dump")
    lines.append("-- Generated by etl/dump_insight_cards.py")
    lines.append("BEGIN;\n")

    # County insight cards
    rows = db.query(CountyInsightCard).order_by(
        CountyInsightCard.county_code, CountyInsightCard.year, CountyInsightCard.angle
    ).all()
    lines.append(f"-- county_insight_cards: {len(rows)} rows")
    for r in rows:
        lines.append(
            f"INSERT INTO county_insight_cards (county_code, county_name, year, angle, narrative) "
            f"VALUES ({r.county_code}, {_escape(r.county_name)}, {r.year}, {_escape(r.angle)}, "
            f"{_escape(r.narrative)}) "
            f"ON CONFLICT (county_code, year, angle) DO UPDATE SET narrative = EXCLUDED.narrative;"
        )

    lines.append("")

    # Statewide insights
    rows2 = db.query(StatewideInsight).order_by(
        StatewideInsight.year, StatewideInsight.angle
    ).all()
    lines.append(f"-- statewide_insights: {len(rows2)} rows")
    for r in rows2:
        lines.append(
            f"INSERT INTO statewide_insights (year, angle, narrative, total_crashes, "
            f"total_killed, total_injured, data_source) "
            f"VALUES ({r.year}, {_escape(r.angle)}, {_escape(r.narrative)}, "
            f"{r.total_crashes or 'NULL'}, {r.total_killed or 'NULL'}, "
            f"{r.total_injured or 'NULL'}, {_escape(r.data_source)}) "
            f"ON CONFLICT (year, angle) DO UPDATE SET narrative = EXCLUDED.narrative, "
            f"total_crashes = EXCLUDED.total_crashes, total_killed = EXCLUDED.total_killed, "
            f"total_injured = EXCLUDED.total_injured;"
        )

    lines.append("\nCOMMIT;")

    db.close()

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(rows)} county + {len(rows2)} statewide = {len(rows) + len(rows2)} rows to {output_path}")


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "insight_cards_data.sql"
    run(path)
