"""add data_source to crashes

Revision ID: 1c7805b99ad1
Revises: 69d22ae6
Create Date: 2026-04-13 22:00:50.875585
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7805b99ad1'
down_revision: Union[str, None] = '69d22ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crashes', sa.Column('data_source', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crashes', 'data_source')
    # ### end Alembic commands ###
