"""add hospitals table

Revision ID: 3824f870c7e4
Revises: c87798039303
Create Date: 2026-04-15 00:21:23.522059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3824f870c7e4'
down_revision: Union[str, None] = 'c87798039303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.String(length=20), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bed_capacity', sa.Integer(), nullable=True),
    sa.Column('trauma_center', sa.String(length=50), nullable=True),
    sa.Column('trauma_pediatric', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id')
    )
    op.create_index('ix_hospitals_county', 'hospitals', ['county_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hospitals_county', table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
