"""add speed_limits table

Revision ID: 54905bd0cf53
Revises: 3824f870c7e4
Create Date: 2026-04-15 00:34:30.451215
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54905bd0cf53'
down_revision: Union[str, None] = '3824f870c7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('speed_limit', sa.SmallInteger(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('avg_lanes', sa.Float(), nullable=True),
    sa.Column('total_aadt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_code', 'speed_limit')
    )
    op.create_index('ix_speed_limits_county', 'speed_limits', ['county_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_speed_limits_county', table_name='speed_limits')
    op.drop_table('speed_limits')
    # ### end Alembic commands ###
