"""add stats snapshot (total_crashes, total_killed) to county_insight_cards

The map served a Fresno card saying "126 fatalities from 10,493 crashes"
while the report card said 142 / 10,546 for the same year (2025): the card
was written from an earlier, still-filling-in snapshot of 2025 and nothing
recorded which numbers it was built from, so nothing could tell it had gone
stale. Each card now stores the county-year totals it was generated from;
the API serves a card only while they still match mv_crashes_by_year.

Nullable ADD COLUMNs — instant, no rewrite. Existing rows stay NULL, which
the API treats as "unverified" and does not serve; the generators fill the
columns when they next write a card. The existing table-level SELECT grant
to calsight_api_ro covers new columns automatically, so no re-grant.

Revision ID: 54e417e52c35
Revises: 57fcafe93ab0
Create Date: 2026-09-22 16:54:00.143636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision id generated by `alembic revision` (never hand-written) —
# sequential-looking ids from parallel sessions have collided before.
revision: str = '54e417e52c35'
down_revision: Union[str, None] = '57fcafe93ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("county_insight_cards", sa.Column("total_crashes", sa.Integer(), nullable=True))
    op.add_column("county_insight_cards", sa.Column("total_killed", sa.Integer(), nullable=True))


def downgrade() -> None:
    op.drop_column("county_insight_cards", "total_killed")
    op.drop_column("county_insight_cards", "total_crashes")
