"""add lat/lon columns to snow_stations (snow layer on the water map)

Nullable ADD COLUMNs on a 110-row table — instant, no rewrite, no
CONCURRENTLY needed. Values come from the static MAJOR_SNOW_STATIONS map
(station coordinates from each station's CDEC staMeta page) and are
written by etl/load_snowpack.py on its next run; no data backfill happens
here. Mirrors e09358c7c0d1, which did the same for reservoirs. The
existing table-level SELECT grant to calsight_api_ro covers new columns
automatically, so no re-grant.

Revision ID: 57fcafe93ab0
Revises: e15a88b36527
Create Date: 2026-09-21 19:04:13.642599
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision id generated by `alembic revision` (never hand-written) —
# sequential-looking ids from parallel sessions have collided before.
revision: str = '57fcafe93ab0'
down_revision: Union[str, None] = 'e15a88b36527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("snow_stations", sa.Column("lat", sa.Float(), nullable=True))
    op.add_column("snow_stations", sa.Column("lon", sa.Float(), nullable=True))


def downgrade() -> None:
    op.drop_column("snow_stations", "lon")
    op.drop_column("snow_stations", "lat")
