"""add traffic_volumes table

Revision ID: 6ae19c9ce232
Revises: 29688ee7cd5b
Create Date: 2026-04-14 20:33:09.570064
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae19c9ce232'
down_revision: Union[str, None] = '29688ee7cd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('total_aadt', sa.Integer(), nullable=True),
    sa.Column('segment_count', sa.SmallInteger(), nullable=True),
    sa.Column('avg_aadt_per_segment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_code')
    )
    op.create_index('ix_traffic_volumes_county_code', 'traffic_volumes', ['county_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traffic_volumes_county_code', table_name='traffic_volumes')
    op.drop_table('traffic_volumes')
    # ### end Alembic commands ###
