"""collision_id unique per data_source not globally

Revision ID: 8370189091fa
Revises: 6ae19c9ce232
Create Date: 2026-04-14 20:44:37.398257
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8370189091fa'
down_revision: Union[str, None] = '6ae19c9ce232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crashes_collision_id_key', 'crashes', type_='unique')
    op.create_unique_constraint('uq_crashes_collision_source', 'crashes', ['collision_id', 'data_source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_crashes_collision_source', 'crashes', type_='unique')
    op.create_unique_constraint('crashes_collision_id_key', 'crashes', ['collision_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
