"""add weather table

Revision ID: 86d353cd78c6
Revises: 8370189091fa
Create Date: 2026-04-14 22:38:48.377254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d353cd78c6'
down_revision: Union[str, None] = '8370189091fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('avg_temp_f', sa.Float(), nullable=True),
    sa.Column('max_temp_f', sa.Float(), nullable=True),
    sa.Column('min_temp_f', sa.Float(), nullable=True),
    sa.Column('precipitation_in', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_code', 'year', 'month')
    )
    op.create_index('ix_weather_county_year', 'weather', ['county_code', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_county_year', table_name='weather')
    op.drop_table('weather')
    # ### end Alembic commands ###
