"""add vehicle_registrations and school_locations tables

Revision ID: c87798039303
Revises: 86d353cd78c6
Create Date: 2026-04-15 00:04:37.897741
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87798039303'
down_revision: Union[str, None] = '86d353cd78c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cds_code', sa.String(length=14), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('school_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cds_code')
    )
    op.create_index('ix_school_locations_county', 'school_locations', ['county_code'], unique=False)
    op.create_table('vehicle_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_code', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('ev_vehicles', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['county_code'], ['counties.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_code', 'year')
    )
    op.create_index('ix_vehicle_registrations_county_year', 'vehicle_registrations', ['county_code', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_registrations_county_year', table_name='vehicle_registrations')
    op.drop_table('vehicle_registrations')
    op.drop_index('ix_school_locations_county', table_name='school_locations')
    op.drop_table('school_locations')
    # ### end Alembic commands ###
