"""clear unverified statewide insight totals

The landing page's "California Insight" card served a 2018 gender narrative
with claims no stats back ("Insurance actuaries had known this for decades",
"crash rates nearly four times higher"). statewide_insights rows were
hand-seeded in May 2026 with the year's totals but text that never passed
etl.fact_check, so matching totals say nothing about the text. The API now
serves a statewide row only while its totals equal mv_crashes_by_year (the
county-card rule from 54e417e52c35); clearing the seeded totals retires
every unverified row. generate_llm_cards --statewide and generate_fun_facts
gate their text and write the totals back when they next write a row.

Data-only UPDATE of ~400 rows. Downgrade can't tell which totals were
cleared, and the seeded text shouldn't come back anyway, so it is a no-op.

Revision ID: e6d9f06f7bb0
Revises: 54e417e52c35
Create Date: 2026-09-23 11:53:58.985512
"""
from typing import Sequence, Union

from alembic import op


# Revision id generated by `alembic revision` (never hand-written) —
# sequential-looking ids from parallel sessions have collided before.
revision: str = 'e6d9f06f7bb0'
down_revision: Union[str, None] = '54e417e52c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE statewide_insights SET total_crashes = NULL, total_killed = NULL")


def downgrade() -> None:
    pass
