"""add crash_parties and crash_victims tables

Revision ID: fd0e0a46c42d
Revises: 54905bd0cf53
Create Date: 2026-04-15 01:11:49.475997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0e0a46c42d'
down_revision: Union[str, None] = '54905bd0cf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash_parties',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.BigInteger(), nullable=False),
    sa.Column('collision_id', sa.BigInteger(), nullable=False),
    sa.Column('party_number', sa.SmallInteger(), nullable=True),
    sa.Column('party_type', sa.String(length=30), nullable=True),
    sa.Column('at_fault', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('sobriety', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_year', sa.SmallInteger(), nullable=True),
    sa.Column('vehicle_make', sa.String(length=50), nullable=True),
    sa.Column('speed_limit', sa.SmallInteger(), nullable=True),
    sa.Column('movement', sa.String(length=100), nullable=True),
    sa.Column('safety_equipment', sa.String(length=100), nullable=True),
    sa.Column('cell_phone_use', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'data_source', name='uq_parties_party_source')
    )
    op.create_index('ix_crash_parties_at_fault', 'crash_parties', ['at_fault'], unique=False)
    op.create_index('ix_crash_parties_collision_id', 'crash_parties', ['collision_id'], unique=False)
    op.create_index('ix_crash_parties_gender', 'crash_parties', ['gender'], unique=False)
    op.create_table('crash_victims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('victim_id', sa.BigInteger(), nullable=False),
    sa.Column('collision_id', sa.BigInteger(), nullable=False),
    sa.Column('party_number', sa.SmallInteger(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('injury_severity', sa.String(length=50), nullable=True),
    sa.Column('person_type', sa.String(length=30), nullable=True),
    sa.Column('seat_position', sa.String(length=50), nullable=True),
    sa.Column('safety_equipment', sa.String(length=100), nullable=True),
    sa.Column('ejected', sa.String(length=30), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('victim_id', 'data_source', name='uq_victims_victim_source')
    )
    op.create_index('ix_crash_victims_collision_id', 'crash_victims', ['collision_id'], unique=False)
    op.create_index('ix_crash_victims_gender', 'crash_victims', ['gender'], unique=False)
    op.create_index('ix_crash_victims_injury_severity', 'crash_victims', ['injury_severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crash_victims_injury_severity', table_name='crash_victims')
    op.drop_index('ix_crash_victims_gender', table_name='crash_victims')
    op.drop_index('ix_crash_victims_collision_id', table_name='crash_victims')
    op.drop_table('crash_victims')
    op.drop_index('ix_crash_parties_gender', table_name='crash_parties')
    op.drop_index('ix_crash_parties_collision_id', table_name='crash_parties')
    op.drop_index('ix_crash_parties_at_fault', table_name='crash_parties')
    op.drop_table('crash_parties')
    # ### end Alembic commands ###
