import ReactMarkdown from "react-markdown";
import type { CanvasBlock } from "../../hooks/useStoryCanvas";
import InlineChart from "./InlineChart";

interface Props {
  title: string;
  blocks: CanvasBlock[];
  filterSummary: string;
}

export default function StoryReportView({ title, blocks, filterSummary }: Props) {
  return (
    <div className="bg-white text-gray-900 p-10 w-[720px] font-body">
      <header className="border-b border-gray-200 pb-4 mb-6">
        <p className="text-xs font-bold uppercase tracking-[0.2em] text-gray-500">CalSight · Ask AI Story</p>
        <h2 className="text-2xl font-headline font-bold mt-1">{title.trim() || "Untitled Story"}</h2>
        <p className="text-xs text-gray-500 mt-2">
          {filterSummary} · {new Date().toLocaleDateString()}
        </p>
      </header>

      <div className="space-y-6">
        {blocks.map((block) =>
          block.kind === "answer" ? (
            <article key={block.id} className="space-y-2">
              {block.question && (
                <p className="text-sm font-semibold text-gray-700">{block.question}</p>
              )}
              <div className="prose prose-sm max-w-none text-gray-900">
                <ReactMarkdown>{block.content}</ReactMarkdown>
              </div>
              {block.chart && <InlineChart chart={block.chart} forceLight />}
            </article>
          ) : (
            <p key={block.id} className="font-serif text-gray-800 leading-relaxed whitespace-pre-wrap">
              {block.text}
            </p>
          ),
        )}
      </div>

      <footer className="border-t border-gray-200 mt-8 pt-3 text-[10px] text-gray-400">
        Generated by CalSight Ask AI · AI can hallucinate — verify critical data.
      </footer>
    </div>
  );
}
