name: Enforce PR Dependencies

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: z0al/dependent-issues@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          label: blocked
          keywords: depends on, blocked by
